name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_code_format:
    name: Check Code Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable 
      - name: Check Code Format
        shell: bash
        run: cargo fmt --check

  check_clippy_warnings:
    name: Check Clippy Warnings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable 
          components: clippy
      - name: Check Code Format
        shell: bash
        run: cargo clippy -- --deny warnings

  run_tests:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        rust-version: 
          - stable 
        platform:
          - { os: ubuntu-latest }
          - { os: windows-latest }
          - { os: macos-latest }
    env:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always
      FEATURES: ${{ format(',{0}', matrix.platform.features ) }}
      OPTIONS: ${{ matrix.platform.options }}
    runs-on: ${{ matrix.platform.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: ${{ matrix.rust-version }} 
    - name: Install Dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install -y libsdl2-gfx-dev libsdl2-gfx-1.0-0 
          libsdl2-mixer-dev libsdl2-mixer-2.0-0 libsdl2-image-dev 
          libsdl2-image-2.0-0 xorg xvfb
        else
          echo "$RUNNER_OS not supported."
        fi
    - name: Run tests
      shell: bash
      run: cargo test --verbose $OPTIONS --all-features 
