[package]
name = "quickstart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wolf_engine = {version = "0.15", features = ["logging"]}
wolf_engine_sdl = {path = "../.."}

